### ISSUE TITLE
NPE in MicroProfileProjectInfoCache$MicroProfileProjectInfoWrapper.<init>(MicroProfileProjectInfoCache.java:88)

### ISSUE THREAD

**Issue by apupier** [redhat-developer/quarkus-ls#365]
on VS Code 1.49.0
VS Code Quarkus 1.6.0

In Quarkus tools output channel:
```
[Sep 21, 2020 11:21:27 AM com.redhat.microprofile.ls.MicroProfileLanguageServer initialize
INFO: Initializing MicroProfile server 0.8.0-20200709-1645 with /home/apupier/.sdkman/candidates/java/20.2.0.r11-grl
Sep 21, 2020 11:21:27 AM com.redhat.microprofile.ls.MicroProfileProjectInfoCache lambda$getProjectInfo$0
WARNING: Error while getting MicroProfileProjectInfo (classpath) for 'file:///home/apupier/git/camel-quarkus/integration-tests/main-xml-io/src/main/resources/application.properties'
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at com.redhat.microprofile.ls.commons.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.redhat.microprofile.ls.MicroProfileProjectInfoCache$MicroProfileProjectInfoWrapper.<init>(MicroProfileProjectInfoCache.java:88)
	at com.redhat.microprofile.ls.MicroProfileProjectInfoCache.lambda$getProjectInfoFromCache$1(MicroProfileProjectInfoCache.java:211)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 13 more](`url`)

```

I tried to "Open Folder..." on this project https://github.com/apache/camel-quarkus/tree/master/integration-tests/main-xml-io and call completion in application.properties file

**Comment by fbricon** [comment]
Can you check if you can reproduce with the latest [vscode-microprofile 0.1.0 build](https://download.jboss.org/jbosstools/vscode/snapshots/vscode-microprofile/?C=M;O=D) + [the latest vscode-quarkus 1.7.0 build](https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/?C=M;O=D)?

**Comment by apupier** [comment]
I do not have vscode-microprofile installed currently.

I installed latest VS Code Quarkus 1.7.0 build 433. Extension is not activating as it requires micropofile extension.
I installed latest VS Code Microprofile 0.1.0 build 30. Extensions are activating. I do not have anymore a NPE. But i do not have any completions. In the output channels, I have "Microprofile Tools" but no "Quarkus Tools". The application.properties file is opened and the Language mode is set by default on Quarkus properties.

**Comment by fbricon** [comment]
@angelozerr can you check please?

**Comment by fbricon** [comment]
@apupier check if you get completion support for other, simpler quarkus projects

**Comment by apupier** [comment]
ah found out why.
The project was not compiled locally. I added 
```
<repositories>
	<repository>
		<id>apache.snapshots</id>
		<name>Apache Development Snapshot Repository</name>
		<url>https://repository.apache.org/content/repositories/snapshots/</url>
		<releases>
			<enabled>false</enabled>
		</releases>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
	
</repositories>
```
to fix compilation issues.

I thought that there wasn't need for the project to compile to provide basic completion in application.properties file. And with latest version there is no NPE anymore so seems fine.

**Comment by angelozerr** [comment]
> I thought that there wasn't need for the project to compile to provide basic completion in application.properties file. 

Properties are computed by using JDT classpath, so you need to have a proper pom.xml.

> And with latest version there is no NPE anymore so seems fine.

Great. Thanks for your feedback.
