### ISSUE TITLE
Generate Qute template content from Java data model

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#442]
When Qute template doesn't exists, a codelens in Jva file is displayed with Create title. When we click on it, it generate the proper Qute template file with content coming from Java data model (method parameters + template.data call).

This generation is not finished and must be improved. It is based on the Qute template ls/blob/master/qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/commands/generate.qute.html that it should be improved.

**Comment by fbricon** [comment]
what's missing?

**Comment by angelozerr** [comment]
It misses:

 * tests
 * generate #for when data model is an iterable.
 * other? (I did that very quickly)

**Comment by fbricon** [comment]
indeed, generating a template from 

```java
    @CheckedTemplate
    public static class Templates {
        public static native TemplateInstance hello(String name); 
    }
```

creates:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
	<p>
		name : java.lang.String
		<ul>
			<li>CASE_INSENSITIVE_ORDER: {name.CASE_INSENSITIVE_ORDER}</li>
		</ul>

	</p>
</body>

```

Which quarkus doesn't like one bit:

```
Caused by: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {name.CASE_INSENSITIVE_ORDER}
        - property/method [CASE_INSENSITIVE_ORDER] not found on class [java.lang.String] nor handled by an extension method
        - at ItemResource/hello.qute.html:11
        at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {name.CASE_INSENSITIVE_ORDER}
        - property/method [CASE_INSENSITIVE_ORDER] not found on class [java.lang.String] nor handled by an extension method
        - at ItemResource/hello.qute.html:11
                at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:174)
                ... 11 more
```
