### ISSUE TITLE
Validation issue with {#with}

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#450]
The following snippet validates properly with qute-ls but fails during quarkus build:
```
{#let title="WELCOME" }
	{title} 

	{#with title}
		{blank}
	{/}
	{{title}}
  {/let}
```

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found template problems (2):
[1] Incorrect expression found: {blank}
        - Only type-safe expressions are allowed in the checked template defined via: org.acme.ItemResource$Templates.list(); an expression must be based on a checked template parameter [items], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
        - at ItemResource/list.qute.html:12
```

Another case:
```
{#each item in items}
  {#with item}
	{name}
  {/with}
{each}
```
No error in qute-ls but at build time you get:
```
[2] Incorrect expression found: {name}
        - Only type-safe expressions are allowed in the checked template defined via: org.acme.ItemResource$Templates.list(); an expression must be based on a checked template parameter [items], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
```

@mkouba how come those 2 cases are incorrect in Qute proper?

**Comment by angelozerr** [comment]
After playing with #with it's not possible to use #with with defined variable coming from a section. It should come from the Java data model.

@mkouba  is it the expected behavior? A limitation? Or have you intention to support it?

**Comment by mkouba** [comment]
> how come those 2 cases are incorrect in Qute proper?

So as you know the `{#with}` section sets the current context object and all nested expressions are first resolved against this object. Which is sometimes useful and perfectly OK but does not allow quarkus to perform type-safe validations. And a template used by `@CheckedTemplate` requires validatable expressions by default.

You can do `@CheckedTemplate(requireTypeSafeExpressions = false)` to relax this requirement. Expressions bound to parameter declarations and `@CheckedTemplate` parameters will be validated and others will be just ignored.

Unfortunately, I have no idea how to improve this behavior. But in general, I don't think that the `{#with}` section is often used...

**Comment by angelozerr** [comment]
> After playing with #with it's not possible to use #with with defined variable coming from a section. It should come from the Java data model.

@mkouba coudl you confirm that please?

I mean you can write that:

```
{@org.acme.Item item}
{#with item}
  {name}
{/with}
```

But not :

```
{@org.acme.Item item}
{#let XXXXX=item}
    {#with XXXXX}
        {name}
    {/with}
{/let}
```

**Comment by mkouba** [comment]
> Is it true?

Hm, you can write both of these snippets but `{name}` will not be validated in neither case.

> My second question is do you think in future Qute, it could support it ?

I'm not sure TBH. We would have to automatically consider all expressions nested in a `{#with}` section to be properties of the passed argument, e.g. for `{#with item}` the `{name}` would be considered `{item.name}`. This is IMO inflexible and often inpractical. Maybe we should **deprecate** `{#with}` and encourage users to always use `{#let}` instead.

**Comment by angelozerr** [comment]
> Hm, you can write both of these snippets but {name} will not be validated in neither case.

I though that {name} will be repaced with the value of item.name but it seems that it doesn't work like this.

Here my idea:

1. report error in this case (#with section can be used only with input data model):

```
{@org.acme.Item item}
{#let XXXXX=item}
    {#with XXXXX}
               /\----/\ #with section can be used only with input data model. 
        {name}
    {/with}
{/let}
```

2. In the future report a deprecated diagnostic for #with (I'm wiating a go from you)
3. provide a quick fix which update #with code with #let code.

**Comment by mkouba** [comment]
> I though that {name} will be repaced with the value of item.name but it seems that it doesn't work like this.

No, it doesn't. You wouldn't be able to use the variables/data from the parent context/scope.

> report error in this case (#with section can be used only with input data model):

Well, it's not an error in general but in a template which is connected to a `@CheckedTemplate` which has `requireTypeSafeExpressions=true` (the default) a usage of `#with` would result in an error in most cases (there are exceptions such as an empty section, etc.). So I think it would be useful to provide a quick fix to update `#with` code with the `#let` code in these templates even now.

**Comment by angelozerr** [comment]
> Well, it's not an error in general but in a template which is connected to a @CheckedTemplate which has requireTypeSafeExpressions=true

In standalone use of Qute, it throws an error too. I think it's important to report an error like (You cannot use the variables/data from the parent context/scope.) because me and @fbricon (we are newbie with Qute) had this error because we though we could use the the variables/data from the parent context/scope.

**Comment by mkouba** [comment]
> In standalone use of Qute, it throws an error too. 

What kind of error does it report?

**Comment by angelozerr** [comment]
I have written some test to play with Qute. For instance see https://github.com/redhat-developer/quarkus-ls/blob/10d204feb305a656ab4fa7104357631e139d30cf/qute.ls/com.redhat.qute.ls/src/test/java/toremove/with.qute

You can start with https://github.com/redhat-developer/quarkus-ls/blob/10d204feb305a656ab4fa7104357631e139d30cf/qute.ls/com.redhat.qute.ls/src/test/java/toremove/TestWithQute.java

It works, but if you uncomment https://github.com/redhat-developer/quarkus-ls/blob/10d204feb305a656ab4fa7104357631e139d30cf/qute.ls/com.redhat.qute.ls/src/test/java/toremove/with.qute#L11

```
{#for review in reviews}
      {#with review}
          {price}
      {/with}
  {/for}
```

the call of `{price}` fails:

```
Exception in thread "main" io.quarkus.qute.TemplateException
	at io.quarkus.qute.CompletedStage.get(CompletedStage.java:44)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$3(TemplateImpl.java:110)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:104)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:90)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.render(TemplateImpl.java:55)
	at toremove.TestWithQute.main(TestWithQute.java:26)
Caused by: io.quarkus.qute.TemplateException: Property "price" not found on the base object "java.util.HashMap" in expression {price} in template 1 on line 14
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:208)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:169)
```

I didn't understand why it tried to search on java.util.HashMap although I wanted that it uses price from review. After debugging Qute parser I noticed that it searches from data model (from java.util.HashMap).

**Comment by mkouba** [comment]
Well, first of all it's a runtime problem and not a parser error. And yes, it fails because there is no `price` property defined on the `Review` and `Item` classes and no data for the key `price` were passed to the template. 

Note that:
1. It's a legal template
2. It would not fail if `Review` or `Item` defined the `price` property
3. It would not fail if `price` was specified via `template.data("price", 10)`
4. If `EngineBuilder.strictRendering(true)` then `{price}` would result in `NOT_FOUND` instead

**Comment by angelozerr** [comment]
> And yes, it fails because there is no price property defined on the Review

My bad you are right, sorry! Let me investigate more the problem.
