### ISSUE TITLE
Parameter declaration support  improvement

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#459]
There are some NPE when parameter declaration is used (ex : higlight a class which doesn't define an alias). Completion of classes should be improved (ex : today we return all classes when no class is defined which could be very bad for performance).

In some cases, completion of class doesn't work (ex : when a alias is defined and some class is defined)

When an alias is defined (without class),the apply of completion generate a new alias.

This support has been developedquickly, many tests should be written to be have a parameter declaration more robust.

**Comment by fbricon** [comment]
If you have malformed parameter declaration, i.e {@org}, the server throws an exception:
```
INFO: Resolving Java type `org`.
Dec 01, 2021 10:47:14 AM com.redhat.qute.utils.QutePositionUtility createRange
SEVERE: While creating Range the Offset was a BadLocation
com.redhat.qute.ls.commons.BadLocationException: Negative offset : -1
	at com.redhat.qute.ls.commons.ListLineTracker.getLineNumberOfOffset(ListLineTracker.java:162)
	at com.redhat.qute.ls.commons.ListLineTracker.getPositionAt(ListLineTracker.java:94)
	at com.redhat.qute.ls.commons.TextDocument.positionAt(TextDocument.java:66)
	at com.redhat.qute.parser.template.Template.positionAt(Template.java:72)
	at com.redhat.qute.utils.QutePositionUtility.createRange(QutePositionUtility.java:80)
	at com.redhat.qute.utils.QutePositionUtility.selectAlias(QutePositionUtility.java:63)
	at com.redhat.qute.utils.QuteSearchUtils.searchReferencedObjects(QuteSearchUtils.java:110)
	at com.redhat.qute.services.QuteLinkedEditing.findLinkedEditingRanges(QuteLinkedEditing.java:49)
	at com.redhat.qute.services.QuteLanguageService.findLinkedEditingRanges(QuteLanguageService.java:151)
	at com.redhat.qute.ls.template.TemplateFileTextDocumentService.lambda$linkedEditingRange$19(TemplateFileTextDocumentService.java:237)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by angelozerr** [comment]
Indeed it was a problem that I reported with NPE. I fixed it in my future PR.
