### ISSUE TITLE
NPE in JDTQuarkusManager.processConfigGroup

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#60]
Using a project with this pom.xml:
```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo.bar</groupId>
  <artifactId>toto</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <properties>
    <surefire-plugin.version>2.22.0</surefire-plugin.version>
    <maven.compiler.target>1.8</maven.compiler.target>
    <quarkus.version>0.21.1</quarkus.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${quarkus.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.3-groovy-2.5</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-undertow</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.8</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-keycloak</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemProperties>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
          </systemProperties>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>native-image</goal>
                </goals>
                <configuration>
                  <enableHttpUrlHandler>true</enableHttpUrlHandler>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemProperties>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                  </systemProperties>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
```
completion fails in application.properties with:
```
[Trace - 11:14:15 AM] Sending request 'textDocument/completion - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Dev/demos/here/toto/src/main/resources/application.properties"
    },
    "position": {
        "line": 2,
        "character": 1
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 11:14:15 AM] Received request 'quarkus/projectInfo - (3)'.
Params: {
    "uri": "file:///Users/fbricon/Dev/demos/here/toto/src/main/resources/application.properties"
}


[Trace - 11:14:15 AM] Sending response 'quarkus/projectInfo - (3)'. Processing request took 1617ms
[Trace - 11:14:15 AM] Received response 'textDocument/completion - (1)' in 1627ms. Request failed: Request quarkus/projectInfo failed with message:  (-32603).
[Error - 11:14:15 AM] Request textDocument/completion failed.
  Message: Request quarkus/projectInfo failed with message: 
  Code: -32603 
```
If you look at the java server logs, you can see quarkus.jdt.core failed because of this NPE:
```
[Error - 11:14:15 AM] 29-Aug-2019 11:14:15 AM Error in calling delegate command handler
null
java.lang.NullPointerException
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:326)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processMap(JDTQuarkusManager.java:547)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:415)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:363)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigRoot(JDTQuarkusManager.java:208)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processQuarkusAnnotation(JDTQuarkusManager.java:157)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.access$0(JDTQuarkusManager.java:148)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager$1.acceptSearchMatch(JDTQuarkusManager.java:126)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2166)
    at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.matchAnnotations(ClassFileMatchLocator.java:351)
    at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.matchAnnotations(ClassFileMatchLocator.java:334)
    at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.locateMatches(ClassFileMatchLocator.java:170)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:1965)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1336)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1373)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1492)
    at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:112)
    at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
    at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
    at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
    at com.redhat.quarkus.jdt.core.JDTQuarkusManager.getQuarkusProjectInfo(JDTQuarkusManager.java:118)
    at com.redhat.quarkus.jdt.internal.core.ls.QuarkusDelegateCommandHandler.getQuarkusProjectInfo(QuarkusDelegateCommandHandler.java:97)
    at com.redhat.quarkus.jdt.internal.core.ls.QuarkusDelegateCommandHandler.executeCommand(QuarkusDelegateCommandHandler.java:58)
    at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:206)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:196)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:459)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$41(JDTLanguageServer.java:909)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```
Null check is missing from:
https://github.com/redhat-developer/quarkus-ls/blob/25a5b079d9a0d27584f0e362a71eefa1f05929f7/quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/core/JDTQuarkusManager.java#L326

**Comment by fbricon** [comment]
If I add the null check, there's a different exception later:
```
String index out of range: -15
java.lang.StringIndexOutOfBoundsException: String index out of range: -15
	at java.lang.String.substring(String.java:1967)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.getRawTypeParameters(JDTQuarkusManager.java:527)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processMap(JDTQuarkusManager.java:540)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:415)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:363)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processMap(JDTQuarkusManager.java:547)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:415)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigGroup(JDTQuarkusManager.java:363)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processConfigRoot(JDTQuarkusManager.java:208)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.processQuarkusAnnotation(JDTQuarkusManager.java:157)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.access$0(JDTQuarkusManager.java:148)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager$1.acceptSearchMatch(JDTQuarkusManager.java:126)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2166)
	at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.matchAnnotations(ClassFileMatchLocator.java:351)
	at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.matchAnnotations(ClassFileMatchLocator.java:334)
	at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.locateMatches(ClassFileMatchLocator.java:170)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:1965)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1336)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1373)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1492)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:112)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at com.redhat.quarkus.jdt.core.JDTQuarkusManager.getQuarkusProjectInfo(JDTQuarkusManager.java:118)
	at com.redhat.quarkus.jdt.internal.core.ls.QuarkusDelegateCommandHandler.getQuarkusProjectInfo(QuarkusDelegateCommandHandler.java:97)
	at com.redhat.quarkus.jdt.internal.core.ls.QuarkusDelegateCommandHandler.executeCommand(QuarkusDelegateCommandHandler.java:58)
```

**Comment by fbricon** [comment]
The problem is caused when the quarkus-keycloak extension is added to the pom.xml
