### ISSUE TITLE
JavaFileTextDocumentService doesn't gracefully handle lack of rename support

### ISSUE THREAD

**Issue by rgrunber** [redhat-developer/quarkus-ls#700]
Try to rename some element in a Java file when the Quarkus extension is started.

We retrieve the `TextDocumentService` and call rename on it. However `JavaFileTextDocumentService` doesn't support rename, and will throw an `UnsupportedOperationException`. The rename will still succeed.

https://github.com/redhat-developer/quarkus-ls/blob/635bedf3bc738108f21c228af27dd6d8d22fd8b8/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java#L233-L235

```
[Error - 12:56:35 p.m.] Request textDocument/rename failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at com.redhat.qute.ls.commons.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.services.TextDocumentService.rename(TextDocumentService.java:337)
	at com.redhat.qute.ls.QuteTextDocumentService.rename(QuteTextDocumentService.java:235)
	... 17 more
```

**Comment by rgrunber** [comment]
I think if `AbstractTextDocumentService` just implements a  `return CompletableFuture.completedFuture(null);` then it should fall back to that instead of throwing the `UnsupportedOperationException`

**Comment by datho7561** [comment]
> I think if `AbstractTextDocumentService` just implements a `return CompletableFuture.completedFuture(null);` for `rename()` then it should fall back to that instead of throwing the `UnsupportedOperationException`

tried this, don't think it works. I'll take a look into this issue though

**Comment by angelozerr** [comment]
Indeed it is a bug, JavaFileTextDocumentService  should implement this rename method which should do nothing.

**Comment by rgrunber** [comment]
I just added the `rename` to both instances of `AbstractTextDocumentService` (there's 2, in qute & in lsp4mp), and that fixed it for me, without having to implement anything in `JavaFileTextDocumentService` . The rename still succeeds, just without any errors.

**Comment by angelozerr** [comment]
Indeed you can do that but it is not consistent with other methods. If you prefer doeing that, please update other methods.
